[package]
name = "irradiance"
version = "0.1.0"
authors = ["Joseph Murphy <air.jmurph@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
candela = "^0.2"
